# Generated by Django 4.2 on 2024-03-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_mix_students_product_min_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='access',
        ),
    ]
